[package]
name = "nexusq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
event-listener = "2.5.3"
parking_lot = "0.12.1"

[dev-dependencies]
criterion = "0.4"
tokio = "1.24.2"
multiqueue = "0.3.2"
multiqueue2 = "0.1.7"


[[bench]]
name = "one_to_one"
harness = false