[package]
name = "nexusq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
event-listener = "2.5.3"
parking_lot = "0.12.1"
crossbeam-utils = "0.8.14"

[dev-dependencies]
criterion = "0.4"
tokio = "1.24.2"
multiqueue = "0.3.2"
multiqueue2 = "0.1.7"


[profile.release]
lto=true
codegen-units=1
incremental=false
strip=true

[[bench]]
name = "one_to_one"
harness = false

[[bench]]
name = "two_to_two"
harness = false
