[top_comments]
Overview = """
This is a benchmark comparison report.
"""

[table_comments]
throughput = """
Since `fibonacci` is not tail recursive or iterative, all these function calls
are not inlined which makes this version very slow.
"""